### ISSUE TITLE
例子失败，可能是bug？

### ISSUE THREAD

**Issue by Mickey-** [fouber/Issue5#1]
我下载了你的源码，解压后执行
fis release -d ./output
在编译产出的output/目录里的结构是

```
output/---
          |---src/
          |---README.md
          |---a.js
```

仍然有README.md ，a.js等src父级目录里的文件

**PS：写了个build.sh，可以满足在项目根目录执行命令的需求了，fis-conf.js也就放到src/里去了，只是上面的问题似乎客观存在**

**Comment by fouber** [comment]
@LeftShore 

估计是你本地的fis版本的问题，include功能在1.4.6才加上，请参看 [changelog](https://github.com/fis-dev/fis/blob/master/CHANGELOG.md#146--tue-sep-17-2013)
